### ISSUE TITLE
Service definition for 'Overriding OpenAPI Specification' is wrong

### ISSUE THREAD

**Issue by jmwri** [api-platform/docs#726]
On the page https://api-platform.com/docs/core/swagger/#overriding-the-openapi-specification the example service definition is as follows:

```
# api/config/services.yaml
services:
    'App\Swagger\SwaggerDecorator':
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@App\Swagger\SwaggerDecorator.inner' ]
        autoconfigure: false
```

This used to work, although it seems a new service has been added:

```
<service id="api_platform.swagger.normalizer.api_gateway" class="ApiPlatform\Core\Swagger\Serializer\ApiGatewayNormalizer" public="false" decorates="api_platform.swagger.normalizer.documentation">
    <argument type="service" id="api_platform.swagger.normalizer.api_gateway.inner" />
    <tag name="serializer.normalizer" priority="17" />
</service>
```

This service now takes precedence over the custom `SwaggerDecorator`. The correct service definition should be:

```
# api/config/services.yaml
services:
    'App\Swagger\SwaggerDecorator':
        decorates: 'api_platform.swagger.normalizer.api_gateway'
        arguments: [ '@App\Swagger\SwaggerDecorator.inner' ]
        autoconfigure: false
```

Was this change mentioned anywhere?

**Comment by dunglas** [comment]
It has been fixed in Symfony 2.4.

**Comment by jmwri** [comment]
This is my `composer.json`:

```
"require": {
     "php": "^7.2.0",
     "ext-ctype": "*",
     "ext-iconv": "*",
     "ext-json": "*",
     "api-platform/api-pack": "^1.1",
     "doctrine/doctrine-bundle": "^1.10",
     "doctrine/doctrine-migrations-bundle": "^2.0",
     "doctrine/orm": "^2.6",
     "gesdinet/jwt-refresh-token-bundle": "^0.5.4",
     "lexik/jwt-authentication-bundle": "^2.6",
     "symfony/console": "4.2.*",
     "symfony/dotenv": "4.2.*",
     "symfony/flex": "^1.1",
     "symfony/framework-bundle": "4.2.*",
     "symfony/ldap": "4.2.*",
     "symfony/yaml": "4.2.*",
     "ext-openssl": "*"
 }
```
As you can see I'm using symfony 4.2. Can you show me where it was fixed?

**Comment by dunglas** [comment]
Try `composer req api-platform/req:^2.4@dev`.

**Comment by jmwri** [comment]
I updated api-platform/api-pack to ^1.2 which didn't fix the issue.

```
❯ composer req api-platform/api-pack:^1.2
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 59 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-mbstring (v1.10.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.10.0): Loading from cache
  - Installing symfony/contracts (v1.0.2): Loading from cache
  - Installing symfony/validator (v4.2.3): Downloading (100%)
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/annotations (v1.6.0): Loading from cache
  - Installing doctrine/reflection (v1.0.0): Loading from cache
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.8.0): Loading from cache
  - Installing doctrine/persistence (v1.1.0): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing doctrine/common (v2.10.0): Loading from cache
  - Installing twig/twig (v2.6.2): Loading from cache
  - Installing symfony/twig-bridge (v4.2.3): Downloading (100%)
  - Installing symfony/http-foundation (v4.2.3): Downloading (100%)
  - Installing symfony/event-dispatcher (v4.2.3): Downloading (100%)
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v4.2.3): Downloading (100%)
  - Installing symfony/http-kernel (v4.2.3): Downloading (100%)
  - Installing symfony/filesystem (v4.2.3): Downloading (100%)
  - Installing symfony/config (v4.2.3): Downloading (100%)
  - Installing symfony/twig-bundle (v4.2.3): Downloading (100%)
  - Installing symfony/inflector (v4.2.3): Downloading (100%)
  - Installing symfony/security-core (v4.2.3): Downloading (100%)
  - Installing symfony/property-access (v4.2.3): Downloading (100%)
  - Installing symfony/security-http (v4.2.3): Downloading (100%)
  - Installing symfony/security-guard (v4.2.3): Downloading (100%)
  - Installing symfony/security-csrf (v4.2.3): Downloading (100%)
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/dependency-injection (v4.2.3): Downloading (100%)
  - Installing symfony/security-bundle (v4.2.3): Downloading (100%)
  - Installing symfony/var-exporter (v4.2.3): Downloading (100%)
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/cache (v4.2.3): Downloading (100%)
  - Installing symfony/expression-language (v4.2.3): Downloading (100%)
  - Installing symfony/asset (v4.2.3): Downloading (100%)
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing symfony/routing (v4.2.3): Downloading (100%)
  - Installing symfony/finder (v4.2.3): Downloading (100%)
  - Installing symfony/framework-bundle (v4.2.3): Downloading (100%)
  - Installing nelmio/cors-bundle (1.5.4): Loading from cache
  - Installing symfony/doctrine-bridge (v4.2.3): Downloading (100%)
  - Installing doctrine/doctrine-cache-bundle (1.3.5): Loading from cache
  - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
  - Installing doctrine/dbal (v2.9.2): Loading from cache
  - Installing symfony/console (v4.2.3): Downloading (100%)
  - Installing doctrine/doctrine-bundle (1.10.1): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing doctrine/orm (v2.6.3): Downloading (100%)
  - Installing willdurand/negotiation (v2.3.1): Loading from cache
  - Installing symfony/serializer (v4.2.3): Downloading (100%)
  - Installing symfony/property-info (v4.2.3): Downloading (100%)
  - Installing api-platform/core (v2.3.6): Loading from cache
  - Installing api-platform/api-pack (v1.2.0): Loading from cache
```

What does `api-platform/req` include? I can't find it on packagist.

**Comment by jmwri** [comment]
api-platform/api-pack to ^1.2 did in fact fix the issue. Thanks for your help.

**Comment by guilliamxavier** [comment]
Xref #722
